DROP TABLE IF EXISTS user;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR UNIQUE NOT NULL,
  total_paying INTEGER DEFAULT 0
);

DROP TABLE IF EXISTS invoice;

CREATE TABLE invoice (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR NOT NULL,
  price INTEGER NOT NULL,  
  voucher_id INTEGER,
  voucher_value INTEGER,
  final_price INTEGER
);

DROP TABLE IF EXISTS voucher;

CREATE TABLE voucher (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  code VARHCAR UNIQUE NOT NULL,
  amount INTEGER,
  invoice_id INTEGER NOT NULL,  
  username VARCHAR NOT NULL,  
  status INT NOT NULL DEFAULT 1,  
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expired TIMESTAMP NOT NULL
);
